### PR TITLE
fix Prealloc call failing and properly check for first volume of archive

### PR DESCRIPTION
**Pull request by ChrisJollyAU**
m_File within CurFile is created around line 664 only if UnpackToMemorySize == -1
Prealloc is called assuming the above has been created so I have protected the call the same way

This compiles and works happily on Windows x64

I believe this fixes PR#13

Addition: Changed the check for first volume of archive to not depend on parts of filenames but to read the properties of the archive. Also do not accept encrypted archives

### CODE REVIEW

**Comment by notspiff** [comment]
Just a fyi. I am on a conference so i wont get to it before next week.

**Comment by notspiff** [comment]
looks legit. the unpacktomemory things is my own hack to support direct reads from stored archives and i must have missed the prealloc block. i'm slightly worried about the firstarchive stuff as i believe i had some false negatives there at some point, but i could never figure out if it was corrupt archives or whatnot (as it is supposed to be the way to go about it). i will merge it and keep an eye open for any reports.

**Comment by ChrisJollyAU** [comment]
Strange about the false positives. NotFirstVolume would be a property of the actual archive so definitely would be interesting to see what file has the problem. My kodi library was fine.

There is though one scenario where one would want to open a part that is not the first volume. Consider a multi part rar with multiple files in it and the file you want to open begins in a subsequent part. Currently according to my tests that would not work. I do have a pull request on its way to support that scenario

**Comment by notspiff** [comment]
Right. That was outside my spec but most welcome.

19. sep. 2017 5:42 p.m. skrev "Christopher Jolly" <notifications@github.com

**Comment by notspiff** [comment]
And i wont have that archive, it was back in 2005 when i did this code so...

19. sep. 2017 5:43 p.m. skrev "Arne Morten Kvarving" <cptspiff@gmail.com>:

**Pull request merged**
